name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        rust: [stable]
        os: [ubuntu-latest, macOS-latest, windows-latest]
    steps:
      - name: Setup Rust (with fmt and clippy)
        if: matrix.os == 'ubuntu-latest'
        uses: hecrj/setup-rust-action@master
        with:
          rust-version: ${{ matrix.rust }}
          components: rustfmt, clippy
      - name: Setup Rust
        if: matrix.os != 'ubuntu-latest'
        uses: hecrj/setup-rust-action@master
        with:
          rust-version: ${{ matrix.rust }}
      - name: Install cargo-make
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: --debug cargo-make
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run cargo fmt
        if: matrix.os == 'ubuntu-latest'
        run: cargo make format
      - name: Run cargo clippy
        if: matrix.os == 'ubuntu-latest'
        run: cargo make clippy
      - name: Run tests
        run: cargo make test
