name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        rust: [stable]
        os: [ubuntu-latest, macOS-latest, windows-latest]
    steps:
      - name: Setup Rust (with fmt and clippy)
        uses: hecrj/setup-rust-action@master
        with:
          rust-version: ${{ matrix.rust }}
          components: rustfmt, clippy
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run cargo fmt
        if: matrix.os == 'ubuntu-latest'
        run: cargo fmt --all -- --check
      - name: Run cargo clippy
        if: matrix.os == 'ubuntu-latest'
        run: cargo clippy
      - name: Run tests
        run: cargo test
